import React,{useEffect,useMemo,useState}from"react";
import{Bot,Brain,ChevronRight,Pause,Play,Send,Sparkles}from"lucide-react";
import"./agent-ui.css";

const API=import.meta.env.VITE_API_URL||"https://api.lunchpad.family";
async function request(path,options){const r=await fetch(API+path,options);const d=await r.json();if(!r.ok)throw new Error(d.error||"The agent dropped its sandwich");return d}

export function AgentChat({slug,pad}){
 const[agent,setAgent]=useState(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[note,setNote]=useState("");
 const[messages,setMessages]=useState([]);
 const sessionId=useMemo(()=>{const key=`lunchbox-agent:${slug}`,saved=localStorage.getItem(key);if(saved)return saved;const id=crypto.randomUUID();localStorage.setItem(key,id);return id},[slug]);
 useEffect(()=>{request(`/v1/agents/${slug}`).then(d=>{setAgent(d.agent);if(d.agent)setMessages([{role:"assistant",content:d.agent.welcomeMessage}])}).catch(()=>{}).finally(()=>setLoading(false))},[slug]);
 async function send(e){e.preventDefault();if(!message.trim()||busy)return;const text=message.trim();setMessage("");setMessages(x=>[...x,{role:"user",content:text}]);setBusy(true);setNote("");try{const d=await request(`/v1/agents/${slug}/chat`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sessionId,message:text})});setMessages(x=>[...x,{role:"assistant",content:d.answer}])}catch(e){setNote(e.message)}finally{setBusy(false)}}
 if(loading)return null;
 if(!agent){if(!["agents","ai"].includes(pad.marketType))return null;return <section className="agentShell dormant"><div className="agentIntro"><span className="kicker">AI17Z COMPARTMENT</span><h2><Brain/> This lunchbox needs a brain.</h2><p>The owner can pack a personality, approved knowledge and isolated memory from the dashboard.</p><a href={`/admin/${slug}`}>Open agent kitchen <ChevronRight/></a></div></section>}
 return <section className="agentShell"><div className="agentIntro"><span className="kicker">LUNCHBOX AI17Z · {agent.status}</span><div className="agentName"><span><Bot/></span><div><h2>{agent.name}</h2><p>{agent.personality}</p></div></div><div className="agentBadges"><b>{agent.tone}</b><b>isolated memory</b><b>socials {agent.socialMode}</b></div><p className="agentSafety">Grounded in owner-approved knowledge and verified Lunchbox events. No wallet control. No private keys. No invented returns.</p></div><div className="chatBox"><div className="chatMessages" aria-live="polite">{messages.map((m,i)=><div className={m.role} key={i}><b>{m.role==="assistant"?agent.name:"You"}</b><p>{m.content}</p></div>)}{busy&&<div className="assistant"><b>{agent.name}</b><p>Rummaging through memory…</p></div>}</div>{note&&<div className="notice">{note}</div>}<form onSubmit={send}><input aria-label={`Message ${agent.name}`} disabled={agent.status!=="active"||busy} value={message} onChange={e=>setMessage(e.target.value)} placeholder={agent.status==="active"?"Ask about this coin or lunchpad…":"Agent is taking a lunch break"}/><button aria-label="Send message" disabled={agent.status!=="active"||busy||!message.trim()}><Send/></button></form></div></section>
}

export function AgentStudio({pad,jwt}){
 const[form,setForm]=useState({name:`${pad.name} Lunchmate`,personality:`A sharp, funny guide who knows ${pad.name} and explains it without hype.`,tone:"funny",knowledge:`${pad.name} is a ${pad.marketType} lunchpad on Robinhood Chain. ${pad.description}`,rules:"Never invent token prices, partnerships or returns. Admit when something is unknown.",welcomeMessage:`Hey, I'm the ${pad.name} Lunchmate. Ask me what's packed in this launchpad.`,status:"active",socialMode:"disabled"});
 const[exists,setExists]=useState(false),[busy,setBusy]=useState(false),[note,setNote]=useState("");
 useEffect(()=>{request(`/v1/agent-admin/${pad.id}`,{headers:{authorization:`Bearer ${jwt}`}}).then(d=>{if(d.agent){setExists(true);setForm({...d.agent,knowledge:d.config.knowledge,rules:d.config.rules})}}).catch(()=>{})},[pad.id,jwt]);
 async function save(e){e.preventDefault();setBusy(true);setNote("");try{const d=await request(`/v1/agent-admin/${pad.id}`,{method:"PUT",headers:{"content-type":"application/json",authorization:`Bearer ${jwt}`},body:JSON.stringify(form)});setExists(true);setForm(x=>({...x,...d.agent}));setNote("Agent packed and ready.")}catch(e){setNote(e.message)}finally{setBusy(false)}}
 return <form className="agentStudio" onSubmit={save}><div className="studioHead"><div><span className="kicker">AI17Z AGENT KITCHEN</span><h3><Sparkles/> {exists?"Tune the lunchmate":"Pack a brain"}</h3></div>{exists&&<button type="button" className="pauseButton" onClick={()=>setForm({...form,status:form.status==="active"?"paused":"active"})}>{form.status==="active"?<><Pause/> Pause</>:<><Play/> Wake</>}</button>}</div>{note&&<div className="notice">{note}</div>}<div className="two"><label>Agent name<input required minLength="2" maxLength="48" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Tone<select value={form.tone} onChange={e=>setForm({...form,tone:e.target.value})}><option value="funny">Funny</option><option value="degen">Degen</option><option value="technical">Technical</option><option value="professional">Professional</option><option value="friendly">Friendly</option></select></label></div><label>Personality<textarea required minLength="12" maxLength="600" value={form.personality} onChange={e=>setForm({...form,personality:e.target.value})}/></label><label>Approved knowledge<textarea className="knowledge" required minLength="20" maxLength="12000" value={form.knowledge} onChange={e=>setForm({...form,knowledge:e.target.value})}/><small>Only place verified project facts and official links here.</small></label><label>Extra rules<textarea maxLength="4000" value={form.rules} onChange={e=>setForm({...form,rules:e.target.value})}/></label><label>Welcome message<input required maxLength="240" value={form.welcomeMessage} onChange={e=>setForm({...form,welcomeMessage:e.target.value})}/></label><div className="two"><label>Social mode<select value={form.socialMode} onChange={e=>setForm({...form,socialMode:e.target.value})}><option value="disabled">Disabled</option><option value="drafts">Drafts only</option><option value="approved">Owner-approved only</option></select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="paused">Paused</option></select></label></div><button className="primary" disabled={busy}>{busy?"Packing memory…":exists?"Save agent":"Create agent"}</button></form>
}
