import React,{useEffect,useState}from"react";
import{Activity,AlertTriangle,ArrowRight,CheckCircle2,CircleDollarSign,Rocket,Save,Store,TrendingUp,Users,Wallet,Zap}from"lucide-react";
import{createPublicClient,createWalletClient,custom,defineChain,formatEther,http}from"viem";
import{AgentStudio}from"./agent-ui";
import{ensureRobinhoodChain,useWalletProviders}from"./wallets";
import"./launchify-pages.css";

const API=import.meta.env.VITE_API_URL||"https://lunchbox-api-production.up.railway.app";
const chain=defineChain({id:4663,name:"Robinhood Chain",nativeCurrency:{name:"Ether",symbol:"ETH",decimals:18},rpcUrls:{default:{http:["https://rpc.mainnet.chain.robinhood.com"]}},blockExplorers:{default:{name:"Blockscout",url:"https://robinhoodchain.blockscout.com"}}});
const withdrawAbi=[{type:"function",name:"withdraw",stateMutability:"nonpayable",inputs:[],outputs:[]}];
const modes=[["Community","🍱","Pons V2 · Robinhood-native","community"],["Stocks","📈","Pons V2 · approved stock pairs","stocks"],["AI agents","🤖","AI17Z · agent-powered launches","agents"],["CME Commodities","🌾","CME V6 · live commodity indexes","commodities"],["Culture","🎨","Pons V2 · Robinhood-native","culture"],["Memes","🐸","Pons V2 · Robinhood-native","memes"],["Creators","🎬","Pons V2 · Robinhood-native","creators"],["Gaming","🎮","Pons V2 · Robinhood-native","gaming"]];
const templates=[["Classic tray","Universal and clear"],["Market terminal","Data-heavy trading view"],["Gallery box","Visual-first collections"],["Picnic table","Story and participation"]];
const short=v=>v?v.slice(0,6)+"…"+v.slice(-4):"";
async function json(path,options){const r=await fetch(API+path,options),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Something spilled");return d}
async function auth(wallet,provider){const c=await json("/v1/auth/challenge?wallet="+wallet),signature=await provider.request({method:"personal_sign",params:[c.message,wallet]});return(await json("/v1/auth/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({wallet,signature})})).token}
function MiniHeader(){return <header className="routeHeader"><a className="routeBrand" href="/">🍱 <b>LUNCHBOX</b><small>LAUNCHPAD KITCHEN</small></a><nav><a href="/">Platform</a><a href="/activity">Activity</a><a href="/revenue">Revenue</a><a href="/docs">Docs</a><a href="/treasury">Treasury</a></nav></header>}
function RouteHero({label,title,copy}){return <section className="routeHero"><span className="kicker">{label}</span><h1>{title}</h1><p>{copy}</p></section>}
function Metrics({s={}}){return <div className="opsMetrics"><article><Store/><small>ACTIVE PADS</small><strong>{s.active_pads??s.total_pads??0}</strong></article><article><Rocket/><small>VERIFIED LAUNCHES</small><strong>{s.total_launches||0}</strong></article><article><Users/><small>UNIQUE CREATORS</small><strong>{s.unique_creators||0}</strong></article><article><Activity/><small>LAST 24 HOURS</small><strong>{s.launches_24h||0}</strong></article></div>}

export function TechSections({onBuild}){
 const[stats,setStats]=useState({});
 useEffect(()=>{json("/v1/stats").then(setStats).catch(()=>{})},[]);
 return <><section className="opsBand" id="network"><Metrics s={stats}/></section><section className="fullKitchen" id="markets"><span className="kicker">SYSTEM TOPOLOGY</span><div className="sectionHead"><h2>Pick a lunch lane.</h2></div><div className="modeGrid">{modes.map(([name,emoji,rail,key])=><article key={key}><span>{emoji}</span><h3>{name}</h3><p>{rail}</p><button className="laneAction" onClick={()=>onBuild?.({marketType:key,niche:name,templateKey:["stocks","commodities"].includes(key)?"terminal":key==="culture"?"gallery":"classic"})}>Pack this lane <ArrowRight/></button></article>)}</div></section><section className="fullKitchen" id="templates"><span className="kicker">PAD TEMPLATES</span><div className="sectionHead"><h2>Different boxes. Same rails.</h2></div><div className="templateGrid">{templates.map(([t,c],i)=>{const key=["classic","terminal","gallery","community"][i];return <article key={t}><b>0{i+1}</b><h3>{t}</h3><p>{c}</p><button className="laneAction" onClick={()=>onBuild?.({templateKey:key})}>Use this box <ArrowRight/></button></article>})}</div></section></>
}

export function ActivityPage(){
 const[pads,setPads]=useState([]),[stats,setStats]=useState({});
 useEffect(()=>{Promise.all([json("/v1/pads?limit=100"),json("/v1/stats")]).then(([p,s])=>{setPads(p.pads);setStats(s)}).catch(()=>{})},[]);
 const lanes=[...new Set(pads.map(p=>p.marketType))];
 return <main><MiniHeader/><RouteHero label="ONCHAIN OPERATIONS" title="Live cafeteria overview." copy="Current storefront and launch totals loaded directly from the Lunchbox production API."/><section className="routeBody"><Metrics s={stats}/><div className="dataList"><div><b>MARKET LANE</b><b>ACTIVE PADS</b></div>{lanes.map(m=><div key={m}><span>{m}</span><strong>{pads.filter(p=>p.marketType===m).length}</strong></div>)}</div></section></main>
}
export function RevenuePage(){
 const[pads,setPads]=useState([]);useEffect(()=>{json("/v1/pads?limit=100").then(d=>setPads(d.pads)).catch(()=>{})},[]);
 return <main><MiniHeader/><RouteHero label="DETERMINISTIC FEE ENGINE" title="Fees routed. Ownership protected." copy="Each pad selects a 2–4% creator transaction tax. Every verified Pons launch follows the protected split."/><section className="routeBody"><div className="bigSplit"><article><small>TOKEN CREATOR</small><strong>70%</strong><span>Launching creator</span></article><article><small>PAD OWNER</small><strong>20%</strong><span>Lunchpad business</span></article><article><small>LUNCHBOX</small><strong>10%</strong><span>Protocol rails</span></article></div><div className="dataList"><div><b>LUNCHPAD</b><b>FUTURE LAUNCH TAX</b></div>{pads.map(p=><div key={p.id}><a href={"/pad/"+p.slug}>{p.name}</a><strong>{p.creatorTaxBps/100}%</strong></div>)}</div></section></main>
}
function Doc({id,n,title,children}){return <section id={id}><small>{n}</small><h2>{title}</h2><p>{children}</p></section>}
export function DocsPage(){
 return <main><MiniHeader/><RouteHero label="LUNCHBOX DOCUMENTATION" title="The recipe for launch businesses." copy="Multi-tenant storefronts, verified namespaces, Pons execution, fee routing and operating dashboards on Robinhood Chain."/><section className="docsLayout"><aside>{["overview","flow","fees","analytics","monitoring","security","api"].map(x=><a href={"#"+x} key={x}>{x}</a>)}</aside><article><Doc id="overview" n="01" title="One box, a full business.">Operators deploy a branded storefront with an owner wallet, public token explorer, configuration, analytics and verified namespace.</Doc><Doc id="flow" n="02" title="Verified launch flow.">Creators choose MetaMask, Trust Wallet or Phantom, upload artwork, deploy a deterministic splitter and confirm the official Pons V2 launch.</Doc><Doc id="fees" n="03" title="Transparent revenue rails.">Each pad selects a 2–4% creator tax: 70% creator, 20% lunchpad owner and 10% protocol.</Doc><Doc id="analytics" n="04" title="Live operating intelligence.">Private owner dashboards include creators, launch windows, failures, claimable revenue and storefront controls.</Doc><Doc id="monitoring" n="05" title="Production health.">Launch failures and unexpected API errors are recorded. The treasury dashboard consolidates incidents across every lunchpad.</Doc><Doc id="security" n="06" title="Wallet-signed ownership.">Lunchbox never receives private keys or recovery phrases. Authentication uses expiring signatures; receipts and fee routes are checked onchain.</Doc><Doc id="api" n="07" title="Production API."><code>GET /health</code><br/><code>GET /v1/stats</code><br/><code>POST /v1/pads</code><br/><code>POST /v1/pads/:id/launches</code><br/><code>GET /v1/pads/:id/analytics</code><br/><code>GET /v1/protocol/monitoring</code></Doc></article></section></main>
}
function ConnectPanel({onConnect}){const wallets=useWalletProviders();return <div className="connectPanel"><h3>Choose wallet</h3><p>Lunchbox connects only to the wallet you choose.</p>{wallets.length?wallets.map(x=><button key={x.key} onClick={()=>onConnect(x.provider)}>{x.label}<ArrowRight/></button>):<div className="notice">No supported wallet detected. Install or unlock MetaMask, Trust Wallet, or Phantom.</div>}</div>}
export function TreasuryPage(){
 const[wallet,setWallet]=useState(""),[provider,setProvider]=useState(null),[data,setData]=useState(null),[note,setNote]=useState("Connect the treasury wallet to open the command kitchen.");
 async function connect(p){try{setNote("");const a=await p.request({method:"eth_requestAccounts"});if(!a?.[0])throw new Error("Wallet did not return an account");setWallet(a[0]);setProvider(p)}catch(e){setNote(e.message)}}
 async function load(){try{const jwt=await auth(wallet,provider),[a,m]=await Promise.all([json("/v1/protocol/analytics",{headers:{authorization:"Bearer "+jwt}}),json("/v1/protocol/monitoring",{headers:{authorization:"Bearer "+jwt}})]);setData({...a,monitoring:m});setNote("Treasury kitchen pass verified.")}catch(e){setNote(e.message)}}
 return <main><MiniHeader/><RouteHero label="TREASURY COMMAND KITCHEN" title="Watch every lunchpad." copy="Wallet-gated network analytics, deployments, failures and protocol health."/><section className="routeBody"><div className="notice">{note}</div>{!wallet&&<ConnectPanel onConnect={connect}/>} {wallet&&!data&&<button className="primary" onClick={load}>Verify {short(wallet)}</button>}{data&&<><Metrics s={data}/><div className="opsMetrics"><article><AlertTriangle/><small>FAILED · 30D</small><strong>{data.failed_launches_30d}</strong></article><article><Wallet/><small>TREASURY BALANCE</small><strong>{Number(formatEther(BigInt(data.monitoring.treasury_balance_wei||"0"))).toFixed(4)} ETH</strong></article><article><Zap/><small>API ERRORS · 24H</small><strong>{data.monitoring.api_errors_24h}</strong></article></div><div className="dataList"><div><b>LUNCHPAD</b><b>LAUNCHES</b></div>{data.pads.map(p=><div key={p.id}><a href={"/pad/"+p.slug}>{p.name}</a><strong>{p.launches}</strong></div>)}</div></>}</section></main>
}
export function AdminPage({slug}){
 const[pad,setPad]=useState(null),[wallet,setWallet]=useState(""),[provider,setProvider]=useState(null),[analytics,setAnalytics]=useState(null),[note,setNote]=useState("Connect the owner or treasury wallet."),[busy,setBusy]=useState(false),[settings,setSettings]=useState(null);
 useEffect(()=>{json("/v1/pads/"+slug).then(d=>{setPad(d.pad);setSettings({description:d.pad.description,accent:d.pad.accent,creatorTaxBps:d.pad.creatorTaxBps,logoUrl:d.pad.logoUrl||""})}).catch(e=>setNote(e.message))},[slug]);
 async function connect(p){try{setNote("");const a=await p.request({method:"eth_requestAccounts"});if(!a?.[0])throw new Error("Wallet did not return an account");setWallet(a[0]);setProvider(p)}catch(e){setNote(e.message)}}
 async function unlock(){try{const jwt=await auth(wallet,provider),a=await json("/v1/pads/"+pad.id+"/analytics",{headers:{authorization:"Bearer "+jwt}});setAnalytics({...a,jwt});setNote(a.access_role==="owner"?"Owner lunch ticket verified.":"Treasury kitchen pass verified.")}catch(e){setNote(e.message)}}
 async function save(e){e.preventDefault();try{setBusy(true);const p=await json("/v1/pads/"+pad.id,{method:"PATCH",headers:{"content-type":"application/json",authorization:"Bearer "+analytics.jwt},body:JSON.stringify(settings)});setPad({...pad,...p});setNote("Storefront settings saved.")}catch(e){setNote(e.message)}finally{setBusy(false)}}
 async function claim(){try{setBusy(true);await ensureRobinhoodChain(provider);const wc=createWalletClient({account:wallet,chain,transport:custom(provider)}),pc=createPublicClient({chain,transport:http()});for(const r of analytics.claimable_routes.filter(x=>BigInt(x.pendingWei)>0n)){const hash=await wc.writeContract({address:r.splitter,abi:withdrawAbi,functionName:"withdraw"});await pc.waitForTransactionReceipt({hash})}setNote("Owner revenue claimed.")}catch(e){setNote(e.message)}finally{setBusy(false)}}
 if(!pad)return <main><MiniHeader/><section className="routeBody"><div className="notice">{note}</div></section></main>;
 return <main><MiniHeader/><RouteHero label="OWNER DASHBOARD" title={pad.name+" command table."} copy="Private analytics, production health, revenue claims, AI17Z and storefront settings."/><section className="routeBody"><div className="notice">{note}</div>{!wallet&&<ConnectPanel onConnect={connect}/>} {wallet&&!analytics&&<button className="primary" onClick={unlock}>Verify admin wallet</button>}{analytics&&<><div className="opsMetrics"><article><Users/><small>CREATORS</small><strong>{analytics.creators}</strong></article><article><Rocket/><small>LAUNCHES</small><strong>{analytics.launches}</strong></article><article><Activity/><small>24 HOURS</small><strong>{analytics.launches_24h}</strong></article><article><TrendingUp/><small>30 DAYS</small><strong>{analytics.launches_30d}</strong></article><article><AlertTriangle/><small>INCIDENTS</small><strong>{analytics.incidents.length}</strong></article><article><CircleDollarSign/><small>CLAIMABLE</small><strong>{Number(formatEther(BigInt(analytics.claimable_operator_wei||"0"))).toFixed(5)} ETH</strong></article></div><div className="adminPanels"><article><h3>Revenue compartment</h3><p><span>Active routes</span><b>{analytics.claimable_routes.length}</b></p><p><span>Available</span><b>{Number(formatEther(BigInt(analytics.claimable_operator_wei||"0"))).toFixed(5)} ETH</b></p>{analytics.access_role==="owner"&&<button className="primary" disabled={busy||BigInt(analytics.claimable_operator_wei||"0")===0n} onClick={claim}>Claim owner revenue</button>}</article><article><h3>Production health</h3>{analytics.incidents.length?analytics.incidents.map(i=><p key={i.id}><span>{i.event_type}</span><b>{i.message}</b></p>):<p><CheckCircle2/><b>No failures in 30 days</b></p>}</article>{analytics.access_role==="owner"&&<form onSubmit={save}><h3>Edit storefront</h3><label>Public description<textarea value={settings.description} onChange={e=>setSettings({...settings,description:e.target.value})}/></label><div className="two"><label>Accent<input type="color" value={settings.accent} onChange={e=>setSettings({...settings,accent:e.target.value})}/></label><label>Future tax<select value={settings.creatorTaxBps} onChange={e=>setSettings({...settings,creatorTaxBps:Number(e.target.value)})}><option value="200">2%</option><option value="300">3%</option><option value="400">4%</option></select></label></div><button className="primary" disabled={busy}><Save/> Save storefront</button></form>} {analytics.access_role==="owner"&&pad.marketType==="agents"&&<AgentStudio pad={pad} jwt={analytics.jwt}/>}</div></>}</section></main>
}
